version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
  flaky-tests-notify: tadashi0713/flaky-tests-notify@1.0.1

parameters:
  notify_flaky_tests:
    type: boolean
    default: true

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install package
          command: python setup.py install -f
      - run:
          name: Run tests
          command: pytest -v --junitxml="Report.xml"
      - store_test_results:
          path: ~/project/Report.xml
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run:
          name: "send flaky notification"
          command:  flaky-tests-notify/notify
          when: on_fail
          
          
  # deploy: # this can be any name you choose
  #   executor: python/default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - heroku/deploy-via-git:
  #         force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
  # notify_flaky_tests:
  #   jobs:
  #     - flaky-tests-notify/notify

