jobs:
  test: 
    executor: python/default 
    steps:
      - checkout 
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: make test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .